package com.nexo;

public class Main {

    public static void main(String[] args) {
	Login GUILogin = new Login();
    }

    /*
    LINEAS DE TEXTPO PARA AUMENTAR LA CANTIDAD DE  BYTES DEL PROGRAMA XDXDXDXDXDLFKSJFLKSDFJLSKDFJSLDKFJSLKDFJLSDKJFLSDKFJSLDKFJSLKDFJSLKDJFSDLKFJSLKDFJSLKDFJSLKDF

     */
}
